export const petBreeds = {
  dog: [
    "American Bulldog",
    "American Cocker Spaniel",
    "American Eskimo Dog",
    "American Pit Bull Terrier",
    "Australian Cattle Dog",
    "Australian Terrier",
    "Basset Hound",
    "Beagle",
    "Bernese Mountain Dog",
    "Black Russian Terrier",
    "Bloodhound",
    "Border Collie",
    "Boston Terrier",
    "Bull Terrier",
    "Bulldog",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chow Chow",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "English Cocker Spaniel",
    "French Bulldog",
    "French Spaniel",
    "German Shepherd",
    "German Spaniel",
    "Golden Retriever",
    "Golden Mixed Breed",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Irish Setter",
    "Irish Terrier",
    "King Charles Spaniel",
    "Labrador Retriever",
    "Maltese",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Miniature Shar Pei",
    "Pekingese",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Rat Terrier",
    "Rottweiler",
    "Russell Terrier",
    "Scottish Terrier",
    "Shar Pei",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "St. Bernard",
    "Yorkshire Terrier"
  ],
  cat: [
    "Abyssinian",
    "British Shorthair",
    "Burmese",
    "Cornish Rex",
    "Devon Rex",
    "Himalayan",
    "Maine Coon",
    "Manx",
    "Persian",
    "Russian Blue",
    "Scottish Fold",
    "Siamese",
    "Sphynx",
    "Turkish Angora",
    "Turkish Van"
  ]
};
